name: Build RK ENTERPRISES APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check project
        run: |
          ls -la
          find . -maxdepth 3 -type f | head -100

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RK-ENTERPRISES-debug-apk
          path: app/build/outputs/apk/debug/*.apk
